var age = 25;
age = 'sfsfd';
age = true;
age = 'hello';
console.log(age);
age = { name: 'lauigi' };
console.log(age);
var mixed = [];
mixed.push(5);
mixed.push('mario');
mixed.push(false);
console.log(mixed);
var ninja;
ninja = { name: "age", age: 23 };
console.log(ninja);
ninja = { name: "fsfs", age: 'fdsfsd' };
console.log(ninja);
